<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Publication extends Model
{
    public $type = null;
    public $category = null;
    public $state = null;
    public $city = null;
    public $street_adress = null;
    public $zip_code = null;
    
    public function __construct($type, $category)
    {
        $this->type = $type;
        $this->category = $category;
    }
    
    public function setLocation($street, $city, $state, $zipcode)
    {
        $this->street_adress = $street;
        $this->city = $city;
        $this->state = $state;
        $this->zip_code = $zipcode;
    }
    
    public static $states_abbr_names = array(
        'AL'=>'Alabama',
        'AK'=>'Alaska',
        'AZ'=>'Arizona',
        'AR'=>'Arkansas',
        'CA'=>'California',
        'CO'=>'Colorado',
        'CT'=>'Connecticut',
        'DE'=>'Delaware',
        'DC'=>'District of Columbia',
        'FL'=>'Florida',
        'GA'=>'Georgia',
        'HI'=>'Hawaii',
        'ID'=>'Idaho',
        'IL'=>'Illinois',
        'IN'=>'Indiana',
        'IA'=>'Iowa',
        'KS'=>'Kansas',
        'KY'=>'Kentucky',
        'LA'=>'Louisiana',
        'ME'=>'Maine',
        'MD'=>'Maryland',
        'MA'=>'Massachusetts',
        'MI'=>'Michigan',
        'MN'=>'Minnesota',
        'MS'=>'Mississippi',
        'MO'=>'Missouri',
        'MT'=>'Montana',
        'NE'=>'Nebraska',
        'NV'=>'Nevada',
        'NH'=>'New Hampshire',
        'NJ'=>'New Jersey',
        'NM'=>'New Mexico',
        'NY'=>'New York',
        'NC'=>'North Carolina',
        'ND'=>'North Dakota',
        'OH'=>'Ohio',
        'OK'=>'Oklahoma',
        'OR'=>'Oregon',
        'PA'=>'Pennsylvania',
        'RI'=>'Rhode Island',
        'SC'=>'South Carolina',
        'SD'=>'South Dakota',
        'TN'=>'Tennessee',
        'TX'=>'Texas',
        'UT'=>'Utah',
        'VT'=>'Vermont',
        'VA'=>'Virginia',
        'WA'=>'Washington',
        'WV'=>'West Virginia',
        'WI'=>'Wisconsin',
        'WY'=>'Wyoming',
    );
    
    public static $states_abbr = array(
        'AL',
        'AK', 
        'AS', 
        'AZ', 
        'AR', 
        'CA', 
        'CO', 
        'CT', 
        'DE', 
        'DC', 
        'FM', 
        'FL', 
        'GA', 
        'GU', 
        'HI', 
        'ID', 
        'IL', 
        'IN', 
        'IA', 
        'KS', 
        'KY', 
        'LA', 
        'ME', 
        'MH', 
        'MD', 
        'MA', 
        'MI',
        'MN', 
        'MS',
        'MO', 
        'MT', 
        'NE',
        'NV',
        'NH', 
        'NJ', 
        'NM', 
        'NY', 
        'NC', 
        'ND',
        'MP', 
        'OH', 
        'OK', 
        'OR', 
        'PW', 
        'PA',
        'RI', 
        'SC',
        'SD', 
        'TN', 
        'TX', 
        'UT', 
        'VT', 
        'VI',
        'VA',
        'WA', 
        'WV', 
        'WI', 
        'WY',
        'Alabama',
        'Alaska',
        'Arizona',
        'Arkansas',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'District of Columbia',
        'Florida',
        'Georgia',
        'Hawaii',
        'Idaho',
        'Illinois',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Maine',
        'Maryland',
        'Massachusetts',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'New York',
        'North Carolina',
        'North Dakota',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Pennsylvania',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Vermont',
        'Virginia',
        'Washington',
        'West Virginia',
        'Wisconsin',
        'Wyoming',
    );
}
